services:
  app:
    build: .
    env_file:
      - .env
    image: ghcr.io/iraserg/eco-map-app:latest
    container_name: eco-map-app
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    env_file:
      - .env
    image: postgis/postgis:15-3.5-alpine
    container_name: eco-map-db
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - eco-map-db:/var/lib/postgresql/data
    command: >
      postgres
      -c shared_buffers=256MB
      -c effective_cache_size=512MB
      -c maintenance_work_mem=128MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=8MB
      -c random_page_cost=2
      -c effective_io_concurrency=1
      -c work_mem=8192kB
volumes:
  eco-map-db:

