server:
  port: 8080
app:
  data-init:
    enabled: true
air:
  quality:
    batch-size: 3
    base-url: "http://air-quality-api.open-meteo.com/v1/air-quality"
    current-parameters:
      - european_aqi
      - pm10
      - pm2_5
      - carbon_monoxide
      - carbon_dioxide
      - nitrogen_dioxide
      - sulphur_dioxide
      - ozone
      - aerosol_optical_depth
      - dust
      - methane
import:
  cities-file: classpath:data/russia_cities.geojson
  regions-file: classpath:data/russia_regions.geojson
  points-file: classpath:data/cities.csv
  water-data-file: classpath:data/water_data.csv
  land-degradation-index-file: classpath:data/land_degradation_index.csv
  soil-pollution-data-file: classpath:data/soil_pollution_data.csv
  radiation-data-file: classpath:data/radiation.csv
  nature-reserve-file: classpath:data/nature-reserve.csv
  cleanup-events-file: classpath:data/cleanup-events.csv
spring:
  application:
    name: eco-map
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show-sql: true
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
logging:
  level:
    root: info
    com.example.eco_map: info
    org.springframework.transaction: warn
    org.springframework.jdbc.datasource.DataSourceTransactionManager: warn
    org.springframework.transaction.interceptor: warn
JWT_SECRET: ${JWT_SECRET_KEY}
JWT_EXPIRATION_TIME_MS: 900000
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always