server:
  port: 8080
app:
  data-init:
    enabled: false
air:
  quality:
    batch-size: 3
    base-url: "http://air-quality-api.open-meteo.com/v1/air-quality"
    current-parameters:
      - european_aqi
      - pm10
      - pm2_5
      - carbon_monoxide
      - carbon_dioxide
      - nitrogen_dioxide
      - sulphur_dioxide
      - ozone
      - aerosol_optical_depth
      - dust
      - methane
import:
  cities-file: russia_cities.geojson
  regions-file: russia_regions.geojson
  points-file: cities.csv
  water-data-file: water_data.csv
  land-degradation-index-file: land_degradation_index.csv
  soil-pollution-data-file: soil_pollution_data.csv
  radiation-data-file: radiation.csv
spring:
  application:
    name: eco-map
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG10Dialect
    show-sql: true
  liquibase:
    change-log: classpath:changelog/db.changelog-master.xml
logging:
  level:
    root: info
    com.example.eco_map: debug
    org.springframework.transaction: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.springframework.transaction.interceptor: TRACE
JWT_SECRET: ${JWT_SECRET_KEY}
JWT_EXPIRATION_TIME_MS: 900000
