name: Docker compose & push to GHCR

on:
  push:
    branches:
      - main

env:
  MAJOR_VERSION: "1"
  MINOR_VERSION: "0"
  PATCH_VERSION: "0"
  IMAGE_NAME: ghcr.io/iraserg/eco-map-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2.0.3
        with:
          envkey_DATABASE_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          envkey_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          envkey_DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          envkey_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          file_name: .env

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Set version and image tag
        run: |
          VERSION="${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"
          IMAGE_TAG="${IMAGE_NAME}:${VERSION}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Update docker-compose.yml image tag
        run: |
          sed -i "s|image: ${IMAGE_NAME}:latest|image: ${IMAGE_TAG}|" docker-compose.yaml

      - name: Build Docker image
        run: |
          docker compose build

      - name: Push Docker image
        run: |
          docker push ${IMAGE_TAG}
